language: python

install: true

addons:
  apt:
    packages:
      - libtest-differences-perl

env:
- PROVEFLAGS="-f"
- PROVEFLAGS="-f -v t_todo"

matrix:
  allow_failures:
  - env: PROVEFLAGS="-f -v t_todo"

script:
  - make test
