.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 Mike Mestnik <cheako+apt_repo@mikemestnik.net>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH Beautify-bash 1 "July 11 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
beautify-bash \- A beautifier for Bash shell scripts written in Python
.SH SYNOPSIS
.B beautify-bash
[\fB\-h\fR|\fB\-t\fR \fITABSIZE\fR]
[<file>|-] ...
.SH DESCRIPTION
This manual page documents briefly the
.B beautify-bash
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics,
.\" respectively.
\fBbeautify-bash\fP is a program that indents and stuff Bash shell scripts.
.SH OPTIONS
.TP
.BR \-t " " \fITABSIZE\fR
Set the size of each indentation
.TP
.BR \-h
Ignores any files and does not process stdin.  Shows usage.
.PP
These programs follow the usual dashes (`-') means use stdin/out.
Files are modified and backups created with tilde (`~') suffix.
